# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('alias', models.CharField(max_length=1000)),
                ('remark', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ins_cmd', models.CharField(max_length=200)),
                ('uins_cmd', models.CharField(max_length=200)),
                ('start_cmd', models.CharField(max_length=100)),
                ('stop_cmd', models.CharField(max_length=100)),
                ('status_cmd', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100)),
            ],
        ),
    ]
