# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0002_configmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_file', models.FileField(upload_to='scripts')),
                ('remark', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='configmodel',
            name='def_parm',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='configmodel',
            name='tar_pkg',
            field=models.FileField(upload_to='files'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='remark',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='software',
            name='remark',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='script',
            name='machines',
            field=models.ManyToManyField(blank=True, to='datamodel.Machine'),
        ),
    ]
