# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0003_auto_20160427_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('config_parm', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('config_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.ConfigModel')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.Script')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.Software')),
            ],
        ),
    ]
