# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0004_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='machine',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='datamodel.Machine'),
            preserve_default=False,
        ),
    ]
