# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0005_application_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_config',
            field=models.BooleanField(default=False),
        ),
    ]
