# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0006_application_is_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_dispatch',
            field=models.BooleanField(default=False),
        ),
    ]
