# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0007_application_is_dispatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('log', models.FileField(upload_to='logs')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.Machine')),
            ],
        ),
    ]
