# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0008_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='log',
            field=models.TextField(blank=True),
        ),
    ]
