# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0009_auto_20160429_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='is_run',
            field=models.BooleanField(default=False),
        ),
    ]
